# Generated by Django 3.2.4 on 2021-06-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('shor_name', models.CharField(max_length=20, verbose_name='nombre corto')),
                ('anulate', models.BooleanField(default=False, verbose_name='anulado')),
            ],
        ),
    ]
