# Generated by Django 3.2.4 on 2021-06-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamentos',
            options={'ordering': ['-name'], 'verbose_name': 'verb_depart', 'verbose_name_plural': 'plural_depart'},
        ),
        migrations.AlterUniqueTogether(
            name='departamentos',
            unique_together={('name', 'shor_name')},
        ),
    ]
